# Generated by Django 2.1 on 2019-12-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
